name: "java distro matrix ubuntu CI workflow"

on:
  push:
    branches: [ main ]


jobs:      

  build-jdk-matrix-job:
    name: "matrix jdk distribution"
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        distro: [microsoft,temurin,zulu,adopt-hotspot,adopt-openj9,liberica]
        jdk: ['17']
        jdk-arch: [x64]   
    runs-on: ${{ matrix.os }} 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distro}}  # See 'Supported distributions' for available options
        java-version: ${{ matrix.jdk }} 
        # architecture: x86 # optional - defaults to x64
        # java-package: jdk # optional (jdk or jre) - defaults to jdk
    - name: "compile"    
      run: |
        javac Sum.java
        java -cp . Sum          

  # build-Eclipse-Temurin-job:
  #   name: "Eclipse Temurin jdk distribution on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v2
  #     with:
  #       distribution: 'temurin' # See 'Supported distributions' for available options
  #       java-version: '17'
  #   - name: "compile"    
  #     run: |
  #       javac Sum.java
  #       java -cp . Sum        