name: "msopenjdk matrix debian docker java CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      # https://crontab.guru/examples.html #every friday at midnight  
      - cron:  '0 0 * * FRI' 

jobs:

  ubuntu-latest-job:
    name: "docker ubuntu latest"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk : [msopenjdk]
        # ver: ['17'] #OK
        ver: ['17','11'] 
        distro: [debian]
        rel: [stretch,buster,bullseye]   
    env:
      distribution: "java"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch      
    - name: "build docker image"
      run: |
        dir=$(pwd)
        cd $dir/dockerfiles/${{matrix.jdk}}/${{matrix.ver}}/${{matrix.distro}}/${{matrix.rel}}
        echo "############################################"
        echo "############################################"
        echo "Building  ${{matrix.jdk}}/${{matrix.ver}}/${{matrix.distro}}/${{matrix.rel}} dockerfile"
        echo "############################################"
        echo "############################################"        
        # docker build -t ${{matrix.distro}}/${{matrix.rel}}/${{matrix.jdk}}-${{matrix.ver}} . 
        docker build . -t  ${{matrix.distro}}/${{matrix.rel}}/${{matrix.jdk}}-${{matrix.ver}} --build-arg DISTRO=${{matrix.distro}} --build-arg DISTRO_VERSION=${{matrix.rel}}  --build-arg JDK_VER=${{matrix.ver}}   
        docker image ls
        docker image history ${{matrix.distro}}/${{matrix.rel}}/${{matrix.jdk}}-${{matrix.ver}}
        docker system df -v               
        docker image inspect ${{matrix.distro}}/${{matrix.rel}}/${{matrix.jdk}}-${{matrix.ver}}                   
